---
# OOB Management network default gateway.
mgmt_gateway: 192.168.123.1
# If ATD is running cEOS, management interface is Management0
# If ATD is running vEOS, management interface is Management1
mgmt_interface: Management0
mgmt_interface_vrf: MGMT

management_security:
  password:
    encryption_key_common: true

# local users
local_users:
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$aQjjIocu2Pxl0baz$.3hUsqFqET6CHtNoc2nKIrmwPY39NYBaG.l2dX1hmiUc46lWorrG7V25b5XeqwSCJnRs4pOe9teK1/5RK8mve/"
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$CK9xRpxGcK.JQ2dr$8L7qtnZmcZt/ySGhpkLF9zumLivW7L0w7mMNeRvx3pDAd6DIH/t6RMKtQ6anLslW6L3r3OmkElLZMmNT1CPVq0"


# Cloud Vision server
cvp_instance_ips:
  - 192.168.122.241
cvp_ingestauth_key: qwerty

# dns servers
name_servers:
 - 8.8.8.8
 - 1.1.1.1

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment
ntp:
  local_interface:
    name: Management0
    vrf: MGMT
  servers:
  - name: time1.google.com
    vrf: MGMT
  - name: time2.google.com
    vrf: MGMT
  - name: time3.google.com
    vrf: MGMT

# dns domain
dns_domain: lab.net
